package com.example.data.model

/**
 * Historical OHLCV (Open, High, Low, Close, Volume) candle representation.
 */
data class OhlcvCandle(
    val timestamp: Long,
    val dateStr: String,
    val open: Double,
    val high: Double,
    val low: Double,
    val close: Double,
    val volume: Long
)

/**
 * Individual simulated trade generated during backtesting.
 */
data class BacktestTrade(
    val tradeNumber: Int,
    val symbol: String,
    val entryDate: String,
    val exitDate: String,
    val type: String = "BUY",
    val entryPrice: Double,
    val exitPrice: Double,
    val quantity: Int,
    val pnl: Double,
    val pnlPercent: Double,
    val holdingDays: Int,
    val exitReason: String,
    val outcome: String // "WIN", "LOSS", "BREAKEVEN"
)

/**
 * Configuration parameters for the backtest execution.
 */
data class BacktestConfig(
    val strategyId: String = "strat-1",
    val strategyName: String = "Momentum Breakout Pilot",
    val symbol: String = "RELIANCE",
    val market: String = "INDIA",
    val timeframeDays: Int = 90,
    val startingCapital: Double = 25000.0,
    val maxRiskPerTradePercent: Double = 1.0,
    val stopLossPercent: Double = 1.5,
    val takeProfitPercent: Double = 3.0,
    val maxHoldingDays: Int = 8
)

/**
 * Comprehensive performance summary generated by the Backtest Simulator.
 */
data class BacktestSummaryResult(
    val config: BacktestConfig,
    val totalTrades: Int,
    val winCount: Int,
    val lossCount: Int,
    val breakevenCount: Int,
    val winRatePercent: Double,
    val startingCapital: Double,
    val finalEquity: Double,
    val netPnl: Double,
    val totalReturnPercent: Double,
    val grossProfit: Double,
    val grossLoss: Double,
    val profitFactor: Double,
    val maxDrawdownPercent: Double,
    val maxDrawdownAmount: Double,
    val avgTradePnl: Double,
    val avgTradeReturnPercent: Double,
    val avgWinPnl: Double,
    val avgLossPnl: Double,
    val payoffRatio: Double,
    val sharpeRatio: Double,
    val avgHoldingDays: Double,
    val trades: List<BacktestTrade>,
    val equityCurve: List<Pair<String, Double>>,
    val qualificationStatus: String,
    val aiCouncilCritique: String
)
